//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllianceSID
    {
        public int SID { get; set; }
        public int AllianceID { get; set; }
        public string SIDName { get; set; }
        public string Remark { get; set; }
        public string SIDStatus { get; set; }
        public string RequestKey { get; set; }
        public string RequestRules { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
    }
}
