//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long OrderID { get; set; }
        public string Status { get; set; }
        public int ResourceID { get; set; }
        public int Count { get; set; }
        public decimal ActualAmount { get; set; }
        public byte ActualCurrencyID { get; set; }
        public decimal cost { get; set; }
        public byte costCurrencyID { get; set; }
        public byte PaymentID { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
    }
}
