//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceRepertory
    {
        public int ResourceID { get; set; }
        public int SID { get; set; }
        public int RepertoryNum { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
    }
}
