//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public int ResourceID { get; set; }
        public byte TypeID { get; set; }
        public byte StoreType { get; set; }
        public string ShowName { get; set; }
        public byte AreaType { get; set; }
        public byte CountryID { get; set; }
        public byte ProvinceID { get; set; }
        public int CityID { get; set; }
        public decimal Price { get; set; }
        public byte PriceCurrencyID { get; set; }
        public decimal SalePrice { get; set; }
        public byte SalePriceCurrencyID { get; set; }
        public string Status { get; set; }
        public string IsEnable { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
    }
}
