//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource_SID_List
    {
        public int SID { get; set; }
        public int ResourceID { get; set; }
        public string ResSIDStatus { get; set; }
        public decimal SettlementPrice { get; set; }
        public byte SettlementPriceCurrencyID { get; set; }
        public System.DateTime DataChange_LastTime { get; set; }
        public System.DateTime DataChange_CreateTime { get; set; }
    }
}
